import '../styles/globals.css'
import Head from "next/head";

function MyApp({Component, pageProps}) {
    return <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
            {/* import tailwind css */}
            <script src="https://cdn.tailwindcss.com"></script>
            {/* import bootstrap */}
            <link
                href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
                rel="stylesheet"
                integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
                crossOrigin="anonymous"/>
            <link href="/styles.css" rel="stylesheet" />
        </Head>
        <Component {...pageProps} />
    </>
}

export default MyApp
