import '../styles/globals.css'
import Head from "next/head";

function MyApp({Component, pageProps}) {
    return <>
        <Head>
            {/* 각 페이지 컴포넌트에서 지정된 title값이 없을 경우 적용됨 */}
            <title>Caffe: 온라인 커피 주문</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
            {/* import tailwind css */}
            <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet" />
            {/* import bootstrap */}
            <link
                href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
                rel="stylesheet"
                integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
                crossOrigin="anonymous"/>
            <link href="/styles.css" rel="stylesheet" />
        </Head>
        <Component {...pageProps} />
    </>
}

export default MyApp
